language: java
script: mvn '-Dmaven.antrun.skip=true' clean package
deploy:
  provider: releases
  api_key: $GH_OATH_TOKEN
  file_glob: true
  file: "target/*.jar"
  skip_cleanup: true
  draft: true
  